apiVersion: apps/v1
kind: Deployment
metadata:
  name: agritech-frontend
  labels:
    app: agritech-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agritech-frontend
  template:
    metadata:
      labels:
        app: agritech-frontend
    spec:
      containers:
      - name: agritech-frontend
        image: <YOUR_ECR_REPOSITORY>/agritech-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8545