apiVersion: apps/v1
kind: Deployment
metadata:
  name: agritech-blockchain
  labels:
    app: agritech-blockchain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agritech-blockchain
  template:
    metadata:
      labels:
        app: agritech-blockchain
    spec:
      containers:
      - name: agritech-blockchain
        image: 603433801149.dkr.ecr.ap-south-1.amazonaws.com/agritech-blockchain
        imagePullPolicy: Always
        ports:
        - containerPort: 8545