apiVersion: v1
kind: Service
metadata:
  name: agritech-blockchain-service
spec:
  type: LoadBalancer
  selector:
    app: agritech-blockchain
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545