apiVersion: apps/v1
kind: Deployment
metadata:
  name: agritech-frontend
  labels:
    app: agritech-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agritech-frontend
  template:
    metadata:
      labels:
        app: agritech-frontend
    spec:
      containers:
      - name: agritech-frontend
        image: 603433801149.dkr.ecr.ap-south-1.amazonaws.com/agritech-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000